class Locators:
    mangocados_css_selector = "div.col-sm-12 a.featured-fruit-name"
    cart_css_selector = ".cart"
    go_checkout_css_selector = ".cta-go-checkout"
    first_name_id = "billing-firstname"
    last_name_id = "billing-lastname"
    address_1_id = "billing-address-1"
    address_2_id = "billing-address-2"
    billing_city_id = "billing-city"
    zip_id = "shipping-zip"
    credit_card_number_id = "credit_card_number"
    cvv_id = "credit_card_cvv"
    im_sure_check_id = "im-sure-check"
    checkout_css_selector = ".cta-checkout"
